In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("dataset/udemy_courses.csv")

# 1. Display Top 10 Rows of The Dataset?

In [3]:
df.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance

# 2. Check Last 5 Rows of The Dataset?

In [4]:
df.tail()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
3673,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,True,100,1040,14,21,All Levels,2.0,2016-06-14T17:36:46Z,Web Development
3674,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,True,25,306,3,42,Beginner Level,3.5,2017-03-10T22:24:30Z,Web Development
3675,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5,2015-12-30T16:41:42Z,Web Development
3676,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,True,50,300,31,38,All Levels,3.0,2016-08-11T19:06:15Z,Web Development
3677,297602,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,True,45,901,36,20,Beginner Level,2.0,2014-09-28T19:51:11Z,Web Development

# 3. Find Shape of Our Dataset (Number of Rows And Number of Columns)?

In [5]:
print("NUmber of Rows:",df.shape[0])
print("NUmber of columns:",df.shape[1])

NUmber of Rows: 3678
NUmber of columns: 12

# 4. Getting Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement?

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3678 entries, 0 to 3677
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   course_id            3678 non-null   int64
 1   course_title         3678 non-null   object
 2   url                  3678 non-null   object
 3   is_paid              3678 non-null   bool
 4   price                3678 non-null   int64
 5   num_subscribers      3678 non-null   int64
 6   num_reviews          3678 non-null   int64
 7   num_lectures         3678 non-null   int64
 8   level                3678 non-null   object
 9   content_duration     3678 non-null   float64
 10  published_timestamp  3678 non-null   object
 11  subject              3678 non-null   object
dtypes: bool(1), float64(1), int64(5), object(5)
memory usage: 319.8+ KB

# 5. Check Null Values In The Dataset?

In [7]:
df.isnull().sum()

course_id              0
course_title           0
url                    0
is_paid                0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
content_duration       0
published_timestamp    0
subject                0
dtype: int64

# 6. Check For Duplicate Data and Drop Them?

In [8]:
df[df.duplicated()]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
787,837322,Essentials of money value: Get a financial Life !,https://www.udemy.com/essentials-of-money-value/,True,20,0,0,20,All Levels,0.616667,2016-05-16T18:28:30Z,Business Finance
788,1157298,Introduction to Forex Trading Business For Beg...,https://www.udemy.com/introduction-to-forex-tr...,True,20,0,0,27,Beginner Level,1.500000,2017-04-23T16:19:01Z,Business Finance
894,1035638,Understanding Financial Statements,https://www.udemy.com/understanding-financial-...,True,25,0,0,10,All Levels,1.000000,2016-12-15T14:56:17Z,Business Finance
1100,1084454,CFA Level 2- Quantitative Methods,https://www.udemy.com/cfa-level-2-quantitative...,True,40,0,0,35,All Levels,5.500000,2017-07-02T14:29:35Z,Business Finance
1473,185526,MicroStation - Células,https://www.udemy.com/microstation-celulas/,True,20,0,0,9,Beginner Level,0.616667,2014-04-15T21:48:55Z,Graphic Design
2561,28295,Learn Web Designing & HTML5/CSS3 Essentials in...,https://www.udemy.com/build-beautiful-html5-we...,True,75,43285,525,24,All Levels,4.000000,2013-01-03T00:55:31Z,Web Development

In [9]:
df.drop_duplicates(inplace=True)

# 7. What are all different subjects for which Udemy is offering courses ?

In [10]:
df["subject"].unique()

array(['Business Finance', 'Graphic Design', 'Musical Instruments',
       'Web Development'], dtype=object)

# 8. Find Out Number of Courses Per Subjects?

In [11]:
df["subject"].value_counts()

subject
Web Development        1199
Business Finance       1191
Musical Instruments     680
Graphic Design          602
Name: count, dtype: int64

# 9.Show all the courses which are Free of Cost?

In [12]:
df[df['is_paid']==False]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
95,1148774,Options Trading 101: The Basics,https://www.udemy.com/options-trading-101-the-...,False,0,1514,66,11,Beginner Level,0.550000,2017-03-23T22:19:57Z,Business Finance
103,133536,Stock Market Investing for Beginners,https://www.udemy.com/the-beginners-guide-to-t...,False,0,50855,2698,15,Beginner Level,1.500000,2013-12-25T19:53:34Z,Business Finance
106,265960,Fundamentals of Forex Trading,https://www.udemy.com/fundamentals-of-forex-tr...,False,0,17160,620,23,All Levels,1.000000,2014-08-29T20:10:38Z,Business Finance
108,923616,Website Investing 101 - Buying & Selling Onlin...,https://www.udemy.com/cash-flow-website-invest...,False,0,6811,151,51,All Levels,2.000000,2016-08-05T17:03:15Z,Business Finance
112,191854,Stock Market Foundations,https://www.udemy.com/how-to-invest-in-the-sto...,False,0,19339,794,9,Beginner Level,2.000000,2014-03-31T21:35:06Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
3638,155640,Building a Search Engine in PHP & MySQL,https://www.udemy.com/creating-a-search-engine...,False,0,10110,379,12,All Levels,2.500000,2014-02-03T18:07:52Z,Web Development
3643,366720,CSS Image filters - The modern web images colo...,https://www.udemy.com/super-awesome-images-wit...,False,0,6315,53,16,All Levels,1.500000,2014-12-10T19:43:40Z,Web Development
3651,1079078,Drupal 8 Site Building,https://www.udemy.com/drupal-8-site-building/,False,0,1942,23,48,All Levels,4.500000,2017-05-02T05:15:52Z,Web Development
3665,21386,Beginner Photoshop to HTML5 and CSS3,https://www.udemy.com/psd-html5-css3/,False,0,73110,1716,22,All Levels,2.000000,2012-07-27T12:54:57Z,Web Development
3668,270976,A how to guide in HTML,https://www.udemy.com/a-how-to-guide-in-html/,False,0,7318,205,8,Beginner Level,0.583333,2014-08-10T20:19:10Z,Web Development

# 10.Show all the courses which are Paid?

In [13]:
df[df['is_paid']==True]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
3673,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,True,100,1040,14,21,All Levels,2.0,2016-06-14T17:36:46Z,Web Development
3674,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,True,25,306,3,42,Beginner Level,3.5,2017-03-10T22:24:30Z,Web Development
3675,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5,2015-12-30T16:41:42Z,Web Development
3676,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,True,50,300,31,38,All Levels,3.0,2016-08-11T19:06:15Z,Web Development
3677,297602,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,True,45,901,36,20,Beginner Level,2.0,2014-09-28T19:51:11Z,Web Development

# 11. Display The Count of Paid and Free Courses?

In [14]:
df['is_paid'].value_counts()

is_paid
True     3362
False     310
Name: count, dtype: int64

# 12. For Which Levels, Udemy Courses Providing The Courses?

In [15]:
df['level'].unique()

array(['All Levels', 'Intermediate Level', 'Beginner Level',
       'Expert Level'], dtype=object)

# 13.Which are Top Selling Courses ?

In [16]:
df.loc[[df['num_subscribers'].idxmax()]]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2827,41295,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,False,0,268923,8629,45,All Levels,10.5,2013-02-14T07:03:41Z,Web Development

# 14.Which are Least Selling Courses ?

In [17]:
df.loc[[df['num_subscribers'].idxmin()]]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
453,837322,Essentials of money value: Get a financial Life !,https://www.udemy.com/essentials-of-money-value/,True,20,0,0,20,All Levels,0.616667,2016-05-16T18:28:30Z,Business Finance

# 15.Show all courses of Graphic Design where the price is below 100 ?

In [18]:
df[(df['subject']=='Graphic Design') & (df['price']<100)]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
1196,1197206,Illustrator CC MasterClass,https://www.udemy.com/illustrator-cc-masterclass/,True,95,462,50,86,All Levels,12.0,2017-05-02T16:41:21Z,Graphic Design
1198,1219520,Adobe Illustrator T-Shirt Design for Merch by ...,https://www.udemy.com/merchbyamazondesign/,True,20,390,44,15,All Levels,1.0,2017-06-13T20:41:14Z,Graphic Design
1202,28556,Discover How to Draw and paint Comics,https://www.udemy.com/learn-to-draw-and-paint/,True,65,8901,424,85,All Levels,62.0,2012-11-21T22:03:54Z,Graphic Design
1203,317278,Typographic Logos: Typography and Lettering fo...,https://www.udemy.com/typographic-logos-typogr...,True,25,4235,427,20,Intermediate Level,1.5,2014-10-16T19:30:01Z,Graphic Design
1204,573064,Photoshop in Ease: Create World Amazing Graph...,https://www.udemy.com/photoshop-knights-become...,True,20,14440,182,26,All Levels,3.0,2015-08-13T21:17:34Z,Graphic Design
...,...,...,...,...,...,...,...,...,...,...,...,...
1793,456388,Adobe Photoshop CC | The Essential Guide,https://www.udemy.com/adobe-photoshop-cc-the-e...,True,20,254,5,81,All Levels,4.5,2015-05-12T00:19:27Z,Graphic Design
1794,955242,Learn to Composite a 2D Action Shot in Photoshop,https://www.udemy.com/3dmotive-learn-to-compos...,True,20,40,2,8,Beginner Level,1.5,2016-09-10T21:38:26Z,Graphic Design
1795,496430,Infographic Design: How To Create Your Own Inf...,https://www.udemy.com/infographic-design-how-t...,True,20,84,8,13,All Levels,2.0,2015-05-12T20:38:58Z,Graphic Design
1796,793246,Autodesk Inventor 2016 : Complete Guide,https://www.udemy.com/learn-autodesk-inventor-...,True,20,23,4,83,Beginner Level,7.5,2016-03-22T20:35:56Z,Graphic Design
1797,547190,Amazing Graphic Design for Beginners,https://www.udemy.com/amazing-graphic-design-f...,True,20,32,10,5,Beginner Level,0.7,2015-07-08T19:58:01Z,Graphic Design

# 16. Find Most Popular Course Title?

In [19]:
df[df.num_reviews==df.num_reviews.max()]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
3230,625204,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,True,200,121584,27445,342,All Levels,43.0,2015-11-02T21:13:27Z,Web Development

In [20]:
df.loc[[df['num_reviews'].idxmax()]]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
3230,625204,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,True,200,121584,27445,342,All Levels,43.0,2015-11-02T21:13:27Z,Web Development

# 17. Display 10 Most Popular Courses As Per Number of Subscribers?

In [21]:
df.sort_values(by='num_subscribers',ascending=False).head(10)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2827,41295,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,False,0,268923,8629,45,All Levels,10.5,2013-02-14T07:03:41Z,Web Development
3032,59014,Coding for Entrepreneurs Basic,https://www.udemy.com/coding-for-entrepreneurs...,False,0,161029,279,27,Beginner Level,3.5,2013-06-09T15:51:55Z,Web Development
3230,625204,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,True,200,121584,27445,342,All Levels,43.0,2015-11-02T21:13:27Z,Web Development
2783,173548,Build Your First Website in 1 Week with HTML5 ...,https://www.udemy.com/build-your-first-website...,False,0,120291,5924,30,Beginner Level,3.0,2014-04-08T16:21:30Z,Web Development
3232,764164,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,True,200,114512,22412,304,All Levels,30.5,2016-03-08T22:28:36Z,Web Development
1896,19421,Free Beginner Electric Guitar Lessons,https://www.udemy.com/beginner-electric-guitar...,False,0,101154,1042,95,Beginner Level,4.5,2012-06-15T17:00:33Z,Musical Instruments
2589,473160,Web Design for Web Developers: Build Beautiful...,https://www.udemy.com/web-design-secrets/,False,0,98867,6512,20,All Levels,3.0,2015-04-13T18:29:47Z,Web Development
2619,94430,Learn Javascript & JQuery From Scratch,https://www.udemy.com/learn-javascript-jquery-...,True,30,84897,2685,10,All Levels,2.0,2013-10-10T15:19:29Z,Web Development
3289,130064,Practical PHP: Master the Basics and Code Dyna...,https://www.udemy.com/code-dynamic-websites/,False,0,83737,4598,45,All Levels,6.5,2014-07-19T03:02:05Z,Web Development
3247,364426,JavaScript: Understanding the Weird Parts,https://www.udemy.com/understand-javascript/,True,175,79612,16976,85,All Levels,11.5,2015-03-12T23:19:54Z,Web Development

# 18. Find Total Number of Courses Related To Python?

In [22]:
df[df['course_title'].str.contains('Python')]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
14,1196544,Python Algo Trading: Sentiment Trading with News,https://www.udemy.com/hedge-fund-strategy-trad...,True,200,294,19,42,All Levels,7.0,2017-04-28T16:41:44Z,Business Finance
30,1170894,Python Algo Stock Trading: Automate Your Trading!,https://www.udemy.com/algorithmic-stock-tradin...,True,95,1165,21,41,Beginner Level,2.5,2017-05-28T23:41:03Z,Business Finance
41,1035472,Python for Finance: Investment Fundamentals & ...,https://www.udemy.com/python-for-finance-inves...,True,195,3811,278,103,All Levels,6.5,2017-03-30T22:17:09Z,Business Finance
147,1070886,Python Algo Trading: FX Trading with Oanda,https://www.udemy.com/python-algo-trading-fx-t...,True,200,453,42,33,Intermediate Level,3.0,2017-03-14T00:39:45Z,Business Finance
334,815482,Stock Technical Analysis with Python,https://www.udemy.com/stock-technical-analysis...,True,50,409,35,46,All Levels,8.0,2016-04-12T00:40:03Z,Business Finance
536,529828,Python for Trading & Investing,https://www.udemy.com/python-for-trading-inves...,True,95,638,25,36,All Levels,5.0,2015-06-17T22:23:31Z,Business Finance
762,1088656,Quantitative Trading Analysis with Python,https://www.udemy.com/quantitative-trading-ana...,True,50,256,17,49,All Levels,5.5,2017-01-27T17:11:28Z,Business Finance
863,902888,Investment Portfolio Analysis with Python,https://www.udemy.com/investment-portfolio-ana...,True,50,209,13,37,All Levels,7.0,2016-07-13T21:40:32Z,Business Finance
1682,546848,Learn to code in Python and learn Adobe Photos...,https://www.udemy.com/learn-to-code-in-python-...,True,50,1132,1,29,All Levels,2.0,2015-07-08T00:15:12Z,Graphic Design
2497,16646,Web Programming with Python,https://www.udemy.com/web-programming-with-pyt...,True,50,35267,217,53,All Levels,4.0,2012-04-25T00:01:43Z,Web Development
2528,391546,Learn Python and Django: Payment Processing,https://www.udemy.com/learn-django-code-accept...,True,70,17714,198,23,All Levels,3.5,2015-02-09T15:37:56Z,Web Development
2553,938560,The Complete Ethical Hacking Course 2.0: Pytho...,https://www.udemy.com/penetration-testing-ethi...,True,195,7827,268,66,All Levels,11.0,2016-09-26T15:08:29Z,Web Development
2570,47963,"Coding for Entrepreneurs: Learn Python, Django...",https://www.udemy.com/coding-for-entrepreneurs/,True,195,23412,799,251,All Levels,45.0,2013-04-08T00:46:14Z,Web Development
2681,477702,Python for Beginners: Python Programming Langu...,https://www.udemy.com/python-course/,True,150,6153,125,84,Beginner Level,5.0,2015-06-14T18:18:57Z,Web Development
2960,270808,Projects in Django and Python,https://www.udemy.com/projects-in-django-and-p...,True,60,1764,53,28,All Levels,6.5,2014-10-21T07:58:07Z,Web Development
3133,574082,"Web Scraping with Python, Ruby & import. io",https://www.udemy.com/web-scraping-with-python...,True,75,973,50,46,All Levels,4.5,2015-08-09T22:16:41Z,Web Development
3138,631128,Complete Python Web Course: Build 8 Python Web...,https://www.udemy.com/the-complete-python-web-...,True,110,7489,941,173,All Levels,16.0,2015-11-08T20:57:35Z,Web Development
3160,368340,Professional Python Web Development Using Flask,https://www.udemy.com/python-flask-course/,True,120,3420,489,102,Beginner Level,14.5,2015-03-04T00:10:36Z,Web Development
3192,1035940,Professional RESTful API Design using Python F...,https://www.udemy.com/restful-api-flask-course/,True,120,578,25,36,Intermediate Level,4.5,2017-01-11T21:15:25Z,Web Development
3194,1063722,Learn Python Django - A Hands-On Course,https://www.udemy.com/learn-python-django-a-ha...,True,50,1339,21,18,Beginner Level,2.0,2017-01-18T21:53:34Z,Web Development
3197,76052,Try Django 1.9 | Build a Blog and Learn Python...,https://www.udemy.com/try-django/,True,50,7407,172,147,All Levels,20.0,2014-03-04T07:12:21Z,Web Development
3200,822444,Python and Django Full Stack Web Developer Boo...,https://www.udemy.com/python-and-django-full-s...,True,200,11832,1883,191,All Levels,31.5,2017-02-24T18:40:55Z,Web Development
3203,970600,REST APIs with Flask and Python,https://www.udemy.com/rest-api-flask-and-python/,True,110,5151,737,115,Intermediate Level,12.5,2016-11-06T19:00:38Z,Web Development
3284,599504,Advanced Scalable Python Web Development Using...,https://www.udemy.com/advanced-python-flask/,True,120,1299,56,71,Intermediate Level,14.0,2016-08-11T22:09:24Z,Web Development
3326,186096,"Core: A Web App Reference Guide for Django, Py...",https://www.udemy.com/coding-for-entrepreneurs...,True,195,2497,98,154,All Levels,26.0,2014-05-29T00:58:43Z,Web Development
3333,1038538,Introduction to QGIS Python Programming,https://www.udemy.com/introduction-to-qgis-pyt...,True,85,197,26,28,Beginner Level,3.5,2016-12-22T00:11:22Z,Web Development
3343,523312,Python Web Programming,https://www.udemy.com/python-web-programming/,True,100,1020,46,60,Beginner Level,6.0,2015-07-01T21:46:36Z,Web Development
3392,70640,Python Programming: Create an Digital Marketpl...,https://www.udemy.com/coding-for-entrepreneurs...,True,195,4198,145,161,All Levels,26.0,2013-10-20T19:53:28Z,Web Development
3507,394832,Fun and creative web engineering with Python a...,https://www.udemy.com/web-engineering-with-pyt...,False,0,10917,319,25,All Levels,2.0,2015-06-09T19:51:50Z,Web Development

# 19. Display 10 Most Popular Python Courses As Per Number of Subscribers?

In [23]:
df.sort_values(by='num_subscribers', ascending=False).head(10)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2827,41295,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,False,0,268923,8629,45,All Levels,10.5,2013-02-14T07:03:41Z,Web Development
3032,59014,Coding for Entrepreneurs Basic,https://www.udemy.com/coding-for-entrepreneurs...,False,0,161029,279,27,Beginner Level,3.5,2013-06-09T15:51:55Z,Web Development
3230,625204,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,True,200,121584,27445,342,All Levels,43.0,2015-11-02T21:13:27Z,Web Development
2783,173548,Build Your First Website in 1 Week with HTML5 ...,https://www.udemy.com/build-your-first-website...,False,0,120291,5924,30,Beginner Level,3.0,2014-04-08T16:21:30Z,Web Development
3232,764164,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,True,200,114512,22412,304,All Levels,30.5,2016-03-08T22:28:36Z,Web Development
1896,19421,Free Beginner Electric Guitar Lessons,https://www.udemy.com/beginner-electric-guitar...,False,0,101154,1042,95,Beginner Level,4.5,2012-06-15T17:00:33Z,Musical Instruments
2589,473160,Web Design for Web Developers: Build Beautiful...,https://www.udemy.com/web-design-secrets/,False,0,98867,6512,20,All Levels,3.0,2015-04-13T18:29:47Z,Web Development
2619,94430,Learn Javascript & JQuery From Scratch,https://www.udemy.com/learn-javascript-jquery-...,True,30,84897,2685,10,All Levels,2.0,2013-10-10T15:19:29Z,Web Development
3289,130064,Practical PHP: Master the Basics and Code Dyna...,https://www.udemy.com/code-dynamic-websites/,False,0,83737,4598,45,All Levels,6.5,2014-07-19T03:02:05Z,Web Development
3247,364426,JavaScript: Understanding the Weird Parts,https://www.udemy.com/understand-javascript/,True,175,79612,16976,85,All Levels,11.5,2015-03-12T23:19:54Z,Web Development

# 20.What are courses that published in year 2015 ?

In [24]:
df[df['published_timestamp'].str.contains('2015')]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
7,403100,"Trading Stock Chart Patterns For Immediate, Ex...",https://www.udemy.com/trading-chart-patterns-f...,True,95,2917,148,23,All Levels,2.5,2015-01-30T22:13:03Z,Business Finance
8,476268,Options Trading 3 : Advanced Stock Profit and ...,https://www.udemy.com/day-trading-stock-option...,True,195,5172,34,38,Expert Level,2.5,2015-05-28T00:14:03Z,Business Finance
10,592338,Forex Trading Secrets of the Pros With Amazon'...,https://www.udemy.com/trading-with-amazons-aws...,True,200,4284,93,76,All Levels,5.0,2015-09-11T16:47:02Z,Business Finance
15,504036,Short Selling: Learn To Sell Stocks Before The...,https://www.udemy.com/short-selling-learn-to-s...,True,75,2276,106,19,Intermediate Level,1.5,2015-06-22T21:18:35Z,Business Finance
17,564966,The Complete Chart Pattern Trading Course: A P...,https://www.udemy.com/make-money-trading-stock...,True,200,2666,115,52,All Levels,4.0,2015-08-10T21:07:35Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
3659,577796,"Simple Javascript: Learn by Doing, Beginners W...",https://www.udemy.com/simple-javascript-learn-...,True,25,2753,10,18,All Levels,2.0,2015-09-07T17:55:11Z,Web Development
3667,523216,The Fastest Way to Create a Website Using Godaddy,https://www.udemy.com/create-your-own-website/,True,30,1454,14,12,Beginner Level,0.5,2015-11-09T20:44:25Z,Web Development
3669,679992,Building Better APIs with GraphQL,https://www.udemy.com/building-better-apis-wit...,True,50,555,89,16,All Levels,2.5,2015-11-29T22:02:02Z,Web Development
3671,667122,Build A Stock Downloader With Visual Studio 20...,https://www.udemy.com/csharpyahoostockdownloader/,True,20,436,36,22,Intermediate Level,1.5,2015-11-19T17:22:47Z,Web Development
3675,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5,2015-12-30T16:41:42Z,Web Development

# 21. Display Category-Wise Count of Posted Subjects [Year Wise] ?

In [31]:
df['year']=pd.to_datetime(df['published_timestamp']).dt.year

In [36]:
df.groupby(['subject','year']).size()

subject              year
Business Finance     2012      6
                     2013     84
                     2014    192
                     2015    339
                     2016    347
                     2017    223
Graphic Design       2012     10
                     2013     23
                     2014     65
                     2015    168
                     2016    181
                     2017    155
Musical Instruments  2012     10
                     2013     39
                     2014    120
                     2015    171
                     2016    228
                     2017    112
Web Development      2011      5
                     2012     19
                     2013     55
                     2014    113
                     2015    336
                     2016    448
                     2017    223
dtype: int64

# 22.What are the Max. Number of Subscribers for Each Level of courses ?

In [42]:
df.groupby('level')['num_subscribers'].max()

level
All Levels            268923
Beginner Level        161029
Expert Level            5172
Intermediate Level     29167
Name: num_subscribers, dtype: int64